[[params.socialIcons]]
name = "github"
url = "https://github.com/samaronybarros"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/sam-barros/"

[[params.socialIcons]]
name = "medium"
url = "https://medium.com/@samarony.barros"

